### ISSUE TITLE
Question: Possible to individually control each LED?

### ISSUE THREAD

**Issue by obfuscatedgenerated** [thegreatrazz/pybledom#5]
I don't know a lot about the protocol, but is it possible to individually address each LED, or is it only the effects provided by the controller that can be used?

It would be easier if the ELK-BLEDOM protocol supports this, and it could be integrated into the library. If not, I'll have to set something up with an arduino.

**Comment by itisrazza** [comment]
No. This protocol is for an LED strip I bought off AliExpress ([something like this](https://www.aliexpress.com/item/1005006628779034.html)) a few years ago. They only support one colour at a time. 

Only the effects on the controller itself are supported, though you can make your own by rapidly sending "set colour" commands yourself.

**Comment by obfuscatedgenerated** [comment]
Ok, that's what I was thinking could be the case. Cheers
